apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/worker.yaml
  - ../base/worker-serviceaccount.yaml
  - ../base/worker-keda-autoscaler.yaml

images:
  - name: us-central1-docker.pkg.dev/development-472321/opentinker/worker
    newTag: latest

commonLabels:
  app.kubernetes.io/part-of: opentinker-workers
  app.kubernetes.io/managed-by: kustomize
