# GCP Secret Store for us-central1 (ESO not deployed on us-east4, so this is only in this overlay)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  labels:
    app.kubernetes.io/name: opentinker-worker
    app.kubernetes.io/part-of: opentinker-workers
spec:
  provider:
    gcpsm:
      projectID: development-472321
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: dev-autopilot-cluster
          serviceAccountRef:
            name: worker
            # namespace set via secret-store-patch.yaml
