apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentinker-dev

resources:
  - ../../base
  - namespace.yaml
  - external-secret.yaml

images:
  - name: us-central1-docker.pkg.dev/development-472321/opentinker/api
    newTag: latest
  - name: us-central1-docker.pkg.dev/development-472321/opentinker/worker
    newTag: latest

patches:
  # Update service account with Workload Identity
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: worker
        annotations:
          iam.gke.io/gcp-service-account: opentinker-worker-dev@development-472321.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: worker

  # Update External Secrets service account
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: external-secrets-sa
        annotations:
          iam.gke.io/gcp-service-account: external-secrets@development-472321.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: external-secrets-sa

commonLabels:
  environment: development
  app.kubernetes.io/instance: opentinker-dev
