apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: development-472321
      auth:
        workloadIdentity:
          clusterLocation: us-east4
          clusterName: us-east4-autopilot-cluster
          serviceAccountRef:
            name: worker
            namespace: opentinker-workers-us-east4
